docker_image: python:3.10-slim
execution_command: python test_wrapper.py
timeout_seconds: 45
target_file: README.md
assets:
- source: test_wrapper.py
  target: test_wrapper.py
- source: test_corpus
  target: test_corpus
- source: ptyprocess-0.7.0-py2.py3-none-any.whl
  target: ptyprocess-0.7.0-py2.py3-none-any.whl
- source: pexpect-4.9.0-py2.py3-none-any.whl
  target: pexpect-4.9.0-py2.py3-none-any.whl
