"""remove_kafka_offset_and_dead_letter

Revision ID: 1b0957bede17
Revises: b50b1d9829ca
Create Date: 2026-06-13 10:36:53.071153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b0957bede17'
down_revision: Union[str, None] = 'b50b1d9829ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dead_letter_records_id', table_name='dead_letter_records')
    op.drop_table('dead_letter_records')
    op.drop_column('submissions', 'kafka_offset')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('kafka_offset', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('dead_letter_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('partition', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_key', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('message_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_failed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_failed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dead_letter_records_pkey')
    )
    op.create_index('ix_dead_letter_records_id', 'dead_letter_records', ['id'], unique=False)
    # ### end Alembic commands ###
