"""initial mysql migration

Revision ID: 746cb246efa2
Revises: 
Create Date: 2026-07-05 16:39:48.755366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '746cb246efa2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['mentors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_admin_id'), 'announcements', ['admin_id'], unique=False)
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('announcement_reads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('announcement_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'user_id', name='uq_announcement_read')
    )
    op.create_index(op.f('ix_announcement_reads_announcement_id'), 'announcement_reads', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_reads_id'), 'announcement_reads', ['id'], unique=False)
    op.create_index(op.f('ix_announcement_reads_user_id'), 'announcement_reads', ['user_id'], unique=False)
    op.create_table('classroom_enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'student_id', name='uq_classroom_student')
    )
    op.create_index(op.f('ix_classroom_enrollments_classroom_id'), 'classroom_enrollments', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_enrollments_id'), 'classroom_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_classroom_enrollments_student_id'), 'classroom_enrollments', ['student_id'], unique=False)
    op.create_table('evaluator_builds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BUILDING', 'SUCCESS', 'FAILED', name='evaluatorstatus'), nullable=False),
    sa.Column('binary_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluator_builds_assignment_id'), 'evaluator_builds', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_evaluator_builds_id'), 'evaluator_builds', ['id'], unique=False)
    op.create_table('grading_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CHALLENGE_ISSUED', 'RUNNING', 'ABORTED', 'PROOF_GENERATED', 'PROOF_SUBMITTED', 'VERIFIED', 'FAILED', 'STARTED', 'IN_PROGRESS', 'SUBMITTED', 'COMPLETED', 'REJECTED', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('proof_nonce', sa.String(length=200), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('pending_payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proof_nonce')
    )
    op.create_index(op.f('ix_grading_sessions_assignment_id'), 'grading_sessions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_grading_sessions_id'), 'grading_sessions', ['id'], unique=False)
    op.create_index('ix_grading_sessions_student_assignment', 'grading_sessions', ['student_id', 'assignment_id'], unique=False)
    op.create_index(op.f('ix_grading_sessions_student_id'), 'grading_sessions', ['student_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('marks_per_question', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_assignment_id'), 'quizzes', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_quizzes_id'), 'quizzes', ['id'], unique=False)
    op.create_table('submission_rate_limits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('last_submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'assignment_id', name='uq_rate_limit_student_assignment')
    )
    op.create_index(op.f('ix_submission_rate_limits_assignment_id'), 'submission_rate_limits', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submission_rate_limits_id'), 'submission_rate_limits', ['id'], unique=False)
    op.create_index(op.f('ix_submission_rate_limits_student_id'), 'submission_rate_limits', ['student_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'TIMEOUT', 'CANCELLED', 'VALIDATION_ERROR', name='submissionstatus'), nullable=False),
    sa.Column('source_type', sa.Enum('GITHUB', 'ZIP', name='submissionsourcetype'), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('zip_object_key', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_id'), 'execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_execution_logs_submission_id'), 'execution_logs', ['submission_id'], unique=False)
    op.create_table('execution_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('container_id', sa.String(length=100), nullable=False),
    sa.Column('wall_time_ms', sa.Integer(), nullable=False),
    sa.Column('cpu_time_ms', sa.Integer(), nullable=False),
    sa.Column('peak_memory_mb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_metrics_id'), 'execution_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_execution_metrics_submission_id'), 'execution_metrics', ['submission_id'], unique=True)
    op.create_table('final_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['grading_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_results_assignment_id'), 'final_results', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_final_results_id'), 'final_results', ['id'], unique=False)
    op.create_index(op.f('ix_final_results_session_id'), 'final_results', ['session_id'], unique=False)
    op.create_index(op.f('ix_final_results_student_id'), 'final_results', ['student_id'], unique=False)
    op.create_table('grading_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'PROCESSING', 'DONE', 'FAILED', 'DEAD_LETTER', name='jobstatus'), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grading_jobs_id'), 'grading_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_grading_jobs_status'), 'grading_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_grading_jobs_submission_id'), 'grading_jobs', ['submission_id'], unique=True)
    op.create_table('proof_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('nonce', sa.String(length=200), nullable=False),
    sa.Column('grader_binary_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_proof', sa.Text(), nullable=False),
    sa.Column('hmac_valid', sa.Boolean(), nullable=False),
    sa.Column('hashes_valid', sa.Boolean(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['grading_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_index(op.f('ix_proof_submissions_assignment_id'), 'proof_submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_proof_submissions_session_id'), 'proof_submissions', ['session_id'], unique=False)
    op.create_index(op.f('ix_proof_submissions_student_id'), 'proof_submissions', ['student_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'student_id', 'attempt_number', name='uq_attempt_per_student')
    )
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_student_id'), 'quiz_attempts', ['student_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), server_default='single', nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('submission_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_outbox_created_at'), 'submission_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_submission_outbox_dispatched_at'), 'submission_outbox', ['dispatched_at'], unique=False)
    op.create_index(op.f('ix_submission_outbox_submission_id'), 'submission_outbox', ['submission_id'], unique=False)
    op.create_table('submission_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('checks_json', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('execution_command', sa.String(length=500), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('oom_killed', sa.Boolean(), nullable=False),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('grader_logs', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_results_id'), 'submission_results', ['id'], unique=False)
    op.create_index(op.f('ix_submission_results_submission_id'), 'submission_results', ['submission_id'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('final_result_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_code', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['final_result_id'], ['final_results.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_assignment_id'), 'certificates', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_certificates_certificate_code'), 'certificates', ['certificate_code'], unique=True)
    op.create_index(op.f('ix_certificates_final_result_id'), 'certificates', ['final_result_id'], unique=False)
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('marks_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_answers_attempt_id'), 'quiz_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_id'), 'quiz_answers', ['id'], unique=False)
    op.create_table('quiz_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_options_id'), 'quiz_options', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_options_question_id'), 'quiz_options', ['question_id'], unique=False)
    op.create_table('quiz_answer_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['quiz_answers.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['quiz_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_answer_options_id'), 'quiz_answer_options', ['id'], unique=False)
    op.drop_index('ix_dead_letter_records_id', table_name='dead_letter_records')
    op.drop_table('dead_letter_records')
    op.add_column('assignments', sa.Column('resource_links', mysql.JSON(), server_default='[]', nullable=False))
    op.add_column('assignments', sa.Column('late_penalty_pct', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('assignments', sa.Column('submission_filename', sa.String(length=300), nullable=True))
    op.add_column('assignments', sa.Column('submission_instructions', sa.Text(), nullable=True))
    op.add_column('assignments', sa.Column('expected_structure', sa.Text(), nullable=True))
    op.add_column('assignments', sa.Column('expected_media_url', sa.String(length=500), nullable=True))
    op.add_column('mentors', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('mentors', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('mentors', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('recipient_id', sa.Uuid(), nullable=False))
    op.add_column('notifications', sa.Column('recipient_type', sa.String(length=20), nullable=False))
    op.add_column('notifications', sa.Column('source_type', sa.String(length=20), server_default='system', nullable=False))
    op.add_column('notifications', sa.Column('source_id', sa.Uuid(), nullable=True))
    op.alter_column('notifications', 'title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.drop_index('ix_notifications_mentor_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.drop_constraint('notifications_ibfk_1', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'mentor_id')
    op.add_column('students', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.add_column('students', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'last_login_at')
    op.drop_column('students', 'locked_until')
    op.drop_column('students', 'failed_login_attempts')
    op.drop_column('students', 'must_change_password')
    op.add_column('notifications', sa.Column('mentor_id', mysql.CHAR(length=32), nullable=False))
    op.create_foreign_key('notifications_ibfk_1', 'notifications', 'mentors', ['mentor_id'], ['id'])
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.create_index('ix_notifications_mentor_id', 'notifications', ['mentor_id'], unique=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('notifications', 'source_id')
    op.drop_column('notifications', 'source_type')
    op.drop_column('notifications', 'recipient_type')
    op.drop_column('notifications', 'recipient_id')
    op.drop_column('mentors', 'last_login_at')
    op.drop_column('mentors', 'locked_until')
    op.drop_column('mentors', 'failed_login_attempts')
    op.drop_column('assignments', 'expected_media_url')
    op.drop_column('assignments', 'expected_structure')
    op.drop_column('assignments', 'submission_instructions')
    op.drop_column('assignments', 'submission_filename')
    op.drop_column('assignments', 'late_penalty_pct')
    op.drop_column('assignments', 'resource_links')
    op.create_table('dead_letter_records',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('partition', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offset', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_key', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('message_value', mysql.TEXT(), nullable=True),
    sa.Column('error_reason', mysql.TEXT(), nullable=True),
    sa.Column('retry_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_failed_at', mysql.DATETIME(), nullable=False),
    sa.Column('last_failed_at', mysql.DATETIME(), nullable=False),
    sa.Column('resolved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('resolved_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_dead_letter_records_id', 'dead_letter_records', ['id'], unique=False)
    op.drop_index(op.f('ix_quiz_answer_options_id'), table_name='quiz_answer_options')
    op.drop_table('quiz_answer_options')
    op.drop_index(op.f('ix_quiz_options_question_id'), table_name='quiz_options')
    op.drop_index(op.f('ix_quiz_options_id'), table_name='quiz_options')
    op.drop_table('quiz_options')
    op.drop_index(op.f('ix_quiz_answers_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_attempt_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_final_result_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_certificate_code'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_assignment_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_submission_results_submission_id'), table_name='submission_results')
    op.drop_index(op.f('ix_submission_results_id'), table_name='submission_results')
    op.drop_table('submission_results')
    op.drop_index(op.f('ix_submission_outbox_submission_id'), table_name='submission_outbox')
    op.drop_index(op.f('ix_submission_outbox_dispatched_at'), table_name='submission_outbox')
    op.drop_index(op.f('ix_submission_outbox_created_at'), table_name='submission_outbox')
    op.drop_table('submission_outbox')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_quiz_attempts_student_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_proof_submissions_student_id'), table_name='proof_submissions')
    op.drop_index(op.f('ix_proof_submissions_session_id'), table_name='proof_submissions')
    op.drop_index(op.f('ix_proof_submissions_assignment_id'), table_name='proof_submissions')
    op.drop_table('proof_submissions')
    op.drop_index(op.f('ix_grading_jobs_submission_id'), table_name='grading_jobs')
    op.drop_index(op.f('ix_grading_jobs_status'), table_name='grading_jobs')
    op.drop_index(op.f('ix_grading_jobs_id'), table_name='grading_jobs')
    op.drop_table('grading_jobs')
    op.drop_index(op.f('ix_final_results_student_id'), table_name='final_results')
    op.drop_index(op.f('ix_final_results_session_id'), table_name='final_results')
    op.drop_index(op.f('ix_final_results_id'), table_name='final_results')
    op.drop_index(op.f('ix_final_results_assignment_id'), table_name='final_results')
    op.drop_table('final_results')
    op.drop_index(op.f('ix_execution_metrics_submission_id'), table_name='execution_metrics')
    op.drop_index(op.f('ix_execution_metrics_id'), table_name='execution_metrics')
    op.drop_table('execution_metrics')
    op.drop_index(op.f('ix_execution_logs_submission_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_submission_rate_limits_student_id'), table_name='submission_rate_limits')
    op.drop_index(op.f('ix_submission_rate_limits_id'), table_name='submission_rate_limits')
    op.drop_index(op.f('ix_submission_rate_limits_assignment_id'), table_name='submission_rate_limits')
    op.drop_table('submission_rate_limits')
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_assignment_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_grading_sessions_student_id'), table_name='grading_sessions')
    op.drop_index('ix_grading_sessions_student_assignment', table_name='grading_sessions')
    op.drop_index(op.f('ix_grading_sessions_id'), table_name='grading_sessions')
    op.drop_index(op.f('ix_grading_sessions_assignment_id'), table_name='grading_sessions')
    op.drop_table('grading_sessions')
    op.drop_index(op.f('ix_evaluator_builds_id'), table_name='evaluator_builds')
    op.drop_index(op.f('ix_evaluator_builds_assignment_id'), table_name='evaluator_builds')
    op.drop_table('evaluator_builds')
    op.drop_index(op.f('ix_classroom_enrollments_student_id'), table_name='classroom_enrollments')
    op.drop_index(op.f('ix_classroom_enrollments_id'), table_name='classroom_enrollments')
    op.drop_index(op.f('ix_classroom_enrollments_classroom_id'), table_name='classroom_enrollments')
    op.drop_table('classroom_enrollments')
    op.drop_index(op.f('ix_announcement_reads_user_id'), table_name='announcement_reads')
    op.drop_index(op.f('ix_announcement_reads_id'), table_name='announcement_reads')
    op.drop_index(op.f('ix_announcement_reads_announcement_id'), table_name='announcement_reads')
    op.drop_table('announcement_reads')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_admin_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
