"""Add Celery grading tables

Revision ID: b50b1d9829ca
Revises: b725bc78516d
Create Date: 2026-06-12 16:41:12.132235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50b1d9829ca'
down_revision: Union[str, None] = 'b725bc78516d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_id'), 'execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_execution_logs_submission_id'), 'execution_logs', ['submission_id'], unique=False)
    op.create_table('execution_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('container_id', sa.String(length=100), nullable=False),
    sa.Column('wall_time_ms', sa.Integer(), nullable=False),
    sa.Column('cpu_time_ms', sa.Integer(), nullable=False),
    sa.Column('peak_memory_mb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_metrics_id'), 'execution_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_execution_metrics_submission_id'), 'execution_metrics', ['submission_id'], unique=True)
    op.create_table('grading_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'PROCESSING', 'DONE', 'FAILED', 'DEAD_LETTER', name='jobstatus'), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grading_jobs_id'), 'grading_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_grading_jobs_status'), 'grading_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_grading_jobs_submission_id'), 'grading_jobs', ['submission_id'], unique=True)
    op.create_table('submission_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_outbox_created_at'), 'submission_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_submission_outbox_dispatched_at'), 'submission_outbox', ['dispatched_at'], unique=False)
    op.create_index(op.f('ix_submission_outbox_submission_id'), 'submission_outbox', ['submission_id'], unique=False)
    op.alter_column('assignments', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # (Removed redundant create_index for ix_one_active_session_per_student_assignment)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Removed redundant drop_index for ix_one_active_session_per_student_assignment)
    op.alter_column('assignments', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_submission_outbox_submission_id'), table_name='submission_outbox')
    op.drop_index(op.f('ix_submission_outbox_dispatched_at'), table_name='submission_outbox')
    op.drop_index(op.f('ix_submission_outbox_created_at'), table_name='submission_outbox')
    op.drop_table('submission_outbox')
    op.drop_index(op.f('ix_grading_jobs_submission_id'), table_name='grading_jobs')
    op.drop_index(op.f('ix_grading_jobs_status'), table_name='grading_jobs')
    op.drop_index(op.f('ix_grading_jobs_id'), table_name='grading_jobs')
    op.drop_table('grading_jobs')
    op.drop_index(op.f('ix_execution_metrics_submission_id'), table_name='execution_metrics')
    op.drop_index(op.f('ix_execution_metrics_id'), table_name='execution_metrics')
    op.drop_table('execution_metrics')
    op.drop_index(op.f('ix_execution_logs_submission_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    # ### end Alembic commands ###
