"""initial

Revision ID: b725bc78516d
Revises: 
Create Date: 2026-06-11 17:24:00.947939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b725bc78516d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('message_key', sa.String(length=200), nullable=True),
    sa.Column('message_value', sa.Text(), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('first_failed_at', sa.DateTime(), nullable=False),
    sa.Column('last_failed_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_records_id'), 'dead_letter_records', ['id'], unique=False)
    op.create_table('graders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='graderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_graders_id'), 'graders', ['id'], unique=False)
    op.create_table('mentors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'MENTOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    op.create_index(op.f('ix_mentors_username'), 'mentors', ['username'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('ARTIFACT_VALIDATION', 'DETERMINISTIC_EXECUTION', 'FILESYSTEM_VALIDATION', 'GIT_VALIDATION', 'NETWORK_VALIDATION', 'DOCUMENTATION_REVIEW', 'MANUAL_REVIEW', name='assignmentcategory'), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['mentors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.create_index(op.f('ix_assignments_slug'), 'assignments', ['slug'], unique=True)
    op.create_table('classrooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('class_code', sa.String(length=50), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_class_code'), 'classrooms', ['class_code'], unique=True)
    op.create_index(op.f('ix_classrooms_id'), 'classrooms', ['id'], unique=False)
    op.create_index(op.f('ix_classrooms_mentor_id'), 'classrooms', ['mentor_id'], unique=False)
    op.create_table('grader_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grader_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('binary_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grader_id'], ['graders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grader_id', 'version', name='uq_grader_version')
    )
    op.create_index(op.f('ix_grader_versions_grader_id'), 'grader_versions', ['grader_id'], unique=False)
    op.create_index(op.f('ix_grader_versions_id'), 'grader_versions', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_mentor_id'), 'notifications', ['mentor_id'], unique=False)
    op.create_table('used_nonces',
    sa.Column('nonce', sa.String(length=200), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_table('assignment_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('config_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_configs_assignment_id'), 'assignment_configs', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_assignment_configs_id'), 'assignment_configs', ['id'], unique=False)
    op.create_table('assignment_grader_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('grader_id', sa.Uuid(), nullable=False),
    sa.Column('grader_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['grader_id'], ['graders.id'], ),
    sa.ForeignKeyConstraint(['grader_version_id'], ['grader_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'grader_id', name='uq_assignment_grader')
    )
    op.create_index(op.f('ix_assignment_grader_mappings_assignment_id'), 'assignment_grader_mappings', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_grader_mappings_grader_id'), 'assignment_grader_mappings', ['grader_id'], unique=False)
    op.create_index(op.f('ix_assignment_grader_mappings_id'), 'assignment_grader_mappings', ['id'], unique=False)
    op.create_table('classroom_enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'student_id', name='uq_classroom_student')
    )
    op.create_index(op.f('ix_classroom_enrollments_classroom_id'), 'classroom_enrollments', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_enrollments_id'), 'classroom_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_classroom_enrollments_student_id'), 'classroom_enrollments', ['student_id'], unique=False)
    op.create_table('evaluator_builds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BUILDING', 'SUCCESS', 'FAILED', name='evaluatorstatus'), nullable=False),
    sa.Column('binary_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluator_builds_assignment_id'), 'evaluator_builds', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_evaluator_builds_id'), 'evaluator_builds', ['id'], unique=False)
    op.create_table('grading_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CHALLENGE_ISSUED', 'RUNNING', 'ABORTED', 'PROOF_GENERATED', 'PROOF_SUBMITTED', 'VERIFIED', 'FAILED', 'STARTED', 'IN_PROGRESS', 'SUBMITTED', 'COMPLETED', 'REJECTED', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('proof_nonce', sa.String(length=200), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('pending_payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proof_nonce')
    )
    op.create_index(op.f('ix_grading_sessions_assignment_id'), 'grading_sessions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_grading_sessions_id'), 'grading_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_grading_sessions_student_id'), 'grading_sessions', ['student_id'], unique=False)
    op.create_index('ix_one_active_session_per_student_assignment', 'grading_sessions', ['student_id', 'assignment_id'], unique=True, postgresql_where=sa.text("status IN ('CREATED', 'CHALLENGE_ISSUED', 'RUNNING', 'PROOF_GENERATED', 'STARTED', 'IN_PROGRESS')"))
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'TIMEOUT', 'CANCELLED', 'VALIDATION_ERROR', name='submissionstatus'), nullable=False),
    sa.Column('source_type', sa.Enum('GITHUB', 'ZIP', name='submissionsourcetype'), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('zip_object_key', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('kafka_offset', sa.Integer(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_table('final_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['grading_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_results_assignment_id'), 'final_results', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_final_results_id'), 'final_results', ['id'], unique=False)
    op.create_index(op.f('ix_final_results_session_id'), 'final_results', ['session_id'], unique=False)
    op.create_index(op.f('ix_final_results_student_id'), 'final_results', ['student_id'], unique=False)
    op.create_table('proof_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('nonce', sa.String(length=200), nullable=False),
    sa.Column('grader_binary_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_proof', sa.Text(), nullable=False),
    sa.Column('hmac_valid', sa.Boolean(), nullable=False),
    sa.Column('hashes_valid', sa.Boolean(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['grading_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_index(op.f('ix_proof_submissions_assignment_id'), 'proof_submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_proof_submissions_session_id'), 'proof_submissions', ['session_id'], unique=False)
    op.create_index(op.f('ix_proof_submissions_student_id'), 'proof_submissions', ['student_id'], unique=False)
    op.create_table('submission_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('checks_json', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('execution_command', sa.String(length=500), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('oom_killed', sa.Boolean(), nullable=False),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('grader_logs', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_results_id'), 'submission_results', ['id'], unique=False)
    op.create_index(op.f('ix_submission_results_submission_id'), 'submission_results', ['submission_id'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('final_result_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_code', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['final_result_id'], ['final_results.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_assignment_id'), 'certificates', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_certificates_certificate_code'), 'certificates', ['certificate_code'], unique=True)
    op.create_index(op.f('ix_certificates_final_result_id'), 'certificates', ['final_result_id'], unique=False)
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_final_result_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_certificate_code'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_assignment_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_submission_results_submission_id'), table_name='submission_results')
    op.drop_index(op.f('ix_submission_results_id'), table_name='submission_results')
    op.drop_table('submission_results')
    op.drop_index(op.f('ix_proof_submissions_student_id'), table_name='proof_submissions')
    op.drop_index(op.f('ix_proof_submissions_session_id'), table_name='proof_submissions')
    op.drop_index(op.f('ix_proof_submissions_assignment_id'), table_name='proof_submissions')
    op.drop_table('proof_submissions')
    op.drop_index(op.f('ix_final_results_student_id'), table_name='final_results')
    op.drop_index(op.f('ix_final_results_session_id'), table_name='final_results')
    op.drop_index(op.f('ix_final_results_id'), table_name='final_results')
    op.drop_index(op.f('ix_final_results_assignment_id'), table_name='final_results')
    op.drop_table('final_results')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_one_active_session_per_student_assignment', table_name='grading_sessions', postgresql_where=sa.text("status IN ('CREATED', 'CHALLENGE_ISSUED', 'RUNNING', 'PROOF_GENERATED', 'STARTED', 'IN_PROGRESS')"))
    op.drop_index(op.f('ix_grading_sessions_student_id'), table_name='grading_sessions')
    op.drop_index(op.f('ix_grading_sessions_id'), table_name='grading_sessions')
    op.drop_index(op.f('ix_grading_sessions_assignment_id'), table_name='grading_sessions')
    op.drop_table('grading_sessions')
    op.drop_index(op.f('ix_evaluator_builds_id'), table_name='evaluator_builds')
    op.drop_index(op.f('ix_evaluator_builds_assignment_id'), table_name='evaluator_builds')
    op.drop_table('evaluator_builds')
    op.drop_index(op.f('ix_classroom_enrollments_student_id'), table_name='classroom_enrollments')
    op.drop_index(op.f('ix_classroom_enrollments_id'), table_name='classroom_enrollments')
    op.drop_index(op.f('ix_classroom_enrollments_classroom_id'), table_name='classroom_enrollments')
    op.drop_table('classroom_enrollments')
    op.drop_index(op.f('ix_assignment_grader_mappings_id'), table_name='assignment_grader_mappings')
    op.drop_index(op.f('ix_assignment_grader_mappings_grader_id'), table_name='assignment_grader_mappings')
    op.drop_index(op.f('ix_assignment_grader_mappings_assignment_id'), table_name='assignment_grader_mappings')
    op.drop_table('assignment_grader_mappings')
    op.drop_index(op.f('ix_assignment_configs_id'), table_name='assignment_configs')
    op.drop_index(op.f('ix_assignment_configs_assignment_id'), table_name='assignment_configs')
    op.drop_table('assignment_configs')
    op.drop_table('used_nonces')
    op.drop_index(op.f('ix_notifications_mentor_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_grader_versions_id'), table_name='grader_versions')
    op.drop_index(op.f('ix_grader_versions_grader_id'), table_name='grader_versions')
    op.drop_table('grader_versions')
    op.drop_index(op.f('ix_classrooms_mentor_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_class_code'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_assignments_slug'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_mentors_username'), table_name='mentors')
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_table('mentors')
    op.drop_index(op.f('ix_graders_id'), table_name='graders')
    op.drop_table('graders')
    op.drop_index(op.f('ix_dead_letter_records_id'), table_name='dead_letter_records')
    op.drop_table('dead_letter_records')
    # ### end Alembic commands ###
