"""add expected_structure and expected_media_url to assignments

Revision ID: f4g5h6i7j8k9
Revises: 03318072fc7d
Create Date: 2026-06-23 11:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4g5h6i7j8k9'
down_revision: Union[str, None] = '03318072fc7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('expected_structure', sa.Text(), nullable=True))
    op.add_column('assignments', sa.Column('expected_media_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'expected_media_url')
    op.drop_column('assignments', 'expected_structure')
    # ### end Alembic commands ###