import json
import logging
from graders.base_grader import BaseGrader, GradingResult, CheckResult

logger = logging.getLogger(__name__)

class Week7Grader(BaseGrader):
    """
    Grader for Week 7 (Web Scraping).
    Parses the JSON output generated by test_wrapper.py.
    """
    
    MAX_POINTS = {
        "execution": 20.0,
        "corpus_dir": 20.0,
        "json_schema": 30.0,
        "content_extraction": 30.0
    }

    def grade(self) -> GradingResult:
        max_score = 100.0
        stdout = self.config.get("execution_result", {}).get("stdout", "")
        
        try:
            start_idx = stdout.find("{")
            end_idx = stdout.rfind("}")
            if start_idx != -1 and end_idx != -1:
                json_str = stdout[start_idx:end_idx+1]
                result_data = json.loads(json_str)
            else:
                raise json.JSONDecodeError("No JSON found", stdout, 0)
        except json.JSONDecodeError:
            logger.error(f"Failed to parse wrapper JSON. stdout: {stdout}")
            return GradingResult(
                score=0.0,
                max_score=max_score,
                passed=False,
                checks=[CheckResult(name="Execution", passed=False, marks=0.0, max_marks=max_score, reason="Grader failed to return valid JSON.", hint="")],
                feedback=f"Execution failed or timed out.\nRaw output:\n{stdout[:1000]}"
            )

        breakdown = result_data.get("breakdown", {})
        feedback_messages = result_data.get("feedback", [])

        checks = []
        total_score = 0.0

        for key, points in breakdown.items():
            max_points = self.MAX_POINTS.get(key, 0.0)
            passed = points == max_points
            total_score += points
            
            reason = "Failed"
            for msg in feedback_messages:
                # Find matching feedback message by looking at the start
                if msg.lower().startswith(key.replace("_", " ")):
                    reason = msg
                    break
            if reason == "Failed" and feedback_messages:
                # fallback if we didn't find exact match
                reason = [m for m in feedback_messages if key.split("_")[0] in m.lower()]
                reason = reason[0] if reason else msg
            
            checks.append(CheckResult(
                name=key.replace("_", " ").title(),
                passed=passed,
                marks=float(points),
                max_marks=max_points,
                reason=reason,
                hint=""
            ))

        formatted_feedback = "\n".join(["- " + msg for msg in feedback_messages])

        return GradingResult(
            score=total_score,
            max_score=max_score,
            passed=(total_score == max_score),
            checks=checks,
            feedback=formatted_feedback
        )
