import json
import logging
from graders.base_grader import BaseGrader, GradingResult, CheckResult

logger = logging.getLogger(__name__)

class Week7Grader(BaseGrader):
    """
    Grader for Week 6.
    Parses the JSON output generated by test_wrapper.py.
    """

    def grade(self) -> GradingResult:
        max_score = 100.0
        stdout = self.config.get("execution_result", {}).get("stdout", "")
        
        try:
            # The test_wrapper.py prints a JSON blob to stdout
            # We need to find the JSON in the output. It should be the last line, or we can just parse the whole stdout if it's clean.
            # But the student's program might have printed things to stdout before crashing, or our wrapper captured it.
            # Wait, the wrapper uses capture_output=True, so the student's output is not mixed with the wrapper's print.
            # So stdout should JUST be the JSON.
            json_line = next((line for line in reversed(stdout.strip().splitlines()) if line.strip().startswith("{")), stdout.strip())
            result_data = json.loads(json_line)
        except json.JSONDecodeError:
            logger.error(f"Failed to parse wrapper JSON. stdout: {stdout}")
            return GradingResult(
                score=0.0,
                max_score=max_score,
                passed=False,
                checks=[CheckResult(name="Execution", passed=False, marks=0.0, max_marks=max_score, reason="Grader failed to return valid JSON.", hint="")],
                feedback=f"Execution failed or timed out.\nRaw output:\n{stdout[:1000]}"
            )

        breakdown = result_data.get("breakdown", {})
        feedback_messages = result_data.get("feedback", [])

        checks = []
        total_score = 0.0

        for key, points in breakdown.items():
            max_points = 30.0 if key == "repo_structure" else (10.0 if key == "quit_command" else 20.0)
            passed = points == max_points
            total_score += points
            
            # Find the specific feedback message for this check
            reason = "Failed"
            for msg in feedback_messages:
                if key.replace("_", " ") in msg.lower():
                    reason = msg
                    break
            
            checks.append(CheckResult(
                name=key.replace("_", " ").title(),
                passed=passed,
                marks=float(points),
                max_marks=max_points,
                reason=reason,
                hint=""
            ))

        formatted_feedback = "\n".join(["- " + msg for msg in feedback_messages])

        return GradingResult(
            score=total_score,
            max_score=max_score,
            passed=(total_score == max_score),
            checks=checks,
            feedback=formatted_feedback
        )
